export const WRECKERSAURUS_SCALE = 2.25;
export const WRECKERSAURUS_SOURCE_ART_SCALE = 0.0118;
export const WRECKERSAURUS_ART_SCALE = WRECKERSAURUS_SOURCE_ART_SCALE * WRECKERSAURUS_SCALE;
export const WRECKERSAURUS_HEAD_JAW_ART_SCALE = WRECKERSAURUS_ART_SCALE;
export const WRECKERSAURUS_DRIVE_SPEED = 20;
export const WRECKERSAURUS_MOTOR_TORQUE = 980;
export const WRECKERSAURUS_WHEEL_FRICTION = 9.5;
export const WRECKERSAURUS_SUSPENSION_FREQUENCY = 7.4;
export const WRECKERSAURUS_SUSPENSION_DAMPING = 0.74;
export const WRECKERSAURUS_CHASSIS_DENSITY = 0.75;
export const WRECKERSAURUS_WHEEL_DENSITY = 2.0;
export const WRECKERSAURUS_ARM_SPEED = 2.7;
export const WRECKERSAURUS_DIRECT_TARGET_SPEED = 10.0;
export const WRECKERSAURUS_DIRECT_HEAD_TURN_SPEED = 2.0;
export const WRECKERSAURUS_JAW_OPEN_ANGLE = 0.48;
export const WRECKERSAURUS_JAW_CLOSED_ANGLE = 0.0;
export const WRECKERSAURUS_COLLISION_GROUP = -3;
export const WRECKERSAURUS_FACING_RIGHT = 1;
export const WRECKERSAURUS_FACING_LEFT = -1;
export const WRECKERSAURUS_GAMEPAD_DEADZONE = 0.14;
export const WRECKERSAURUS_FLIP_UPWARD_IMPULSE = 780;
export const WRECKERSAURUS_FLIP_SIDE_IMPULSE = 120;
export const WRECKERSAURUS_FLIP_ANGULAR_IMPULSE = 900;
export const WRECKERSAURUS_FRACTURE_LOAD_MULTIPLIER = 0.78;
export const WRECKERSAURUS_HEAD_TERRAIN_DAMAGE_SCALE = 2.35;
export const WRECKERSAURUS_JAW_TERRAIN_DAMAGE_SCALE = 3.4;
export const WRECKERSAURUS_TOOTH_TERRAIN_DAMAGE_SCALE = 5.8;
export const WRECKERSAURUS_TAIL_TERRAIN_DAMAGE_SCALE = 4.6;
export const WRECKERSAURUS_TAIL_REST_ANGLE = Math.PI / 4;
export const WRECKERSAURUS_TAIL_RAISED_ANGLE = 1.36;
export const WRECKERSAURUS_TAIL_LENGTH = 12;
export const WRECKERSAURUS_TAIL_CENTER = 5.5;
export const WRECKERSAURUS_TAIL_WIDTH = 0.75;
export const WRECKERSAURUS_TAIL_BALL_CENTER = 14.5;
export const WRECKERSAURUS_TAIL_BALL_RADIUS = 3.0907;
export const WRECKERSAURUS_TAIL_BODY_DENSITY = 0.08;
export const WRECKERSAURUS_TAIL_BALL_DENSITY = 0.18;
export const WRECKERSAURUS_TAIL_REST_STIFFNESS = 7500;
export const WRECKERSAURUS_TAIL_RAISED_STIFFNESS = 6000;
export const WRECKERSAURUS_TAIL_SLAM_STIFFNESS = 0;
export const WRECKERSAURUS_TAIL_REST_DAMPING = 1000;
export const WRECKERSAURUS_TAIL_RAISED_DAMPING = 1000;
export const WRECKERSAURUS_TAIL_SLAM_DAMPING = 0;
export const WRECKERSAURUS_TAIL_MAX_TORQUE = 50000;
export const WRECKERSAURUS_TAIL_RAISE_RATE = 2.4;
export const WRECKERSAURUS_TAIL_RELEASE_DURATION = 1.00;
export const WRECKERSAURUS_TAIL_RECOVER_RATE = 1.9;
export const WRECKERSAURUS_TAIL_DOWNSWING_DURATION = 1.00;
export const WRECKERSAURUS_TAIL_DOWNSWING_TORQUE = 40000;
export const WRECKERSAURUS_TAIL_DOWNSWING_IMPULSE = 1000;
export const WRECKERSAURUS_TAIL_DOWNSWING_REACTION_SCALE = 0;
export const WRECKERSAURUS_TAIL_PACKED_MELT_CONTACT_RADIUS_SCALE = 0.02;
export const WRECKERSAURUS_ARM_SERVO = {
  boomAngle: { gain: 3.1, damping: 0.28, speedScale: 1 },
  stickAngle: { gain: 3.35, damping: 0.48, speedScale: 0.96 },
  headAngle: { gain: 1.55, damping: 0.72, speedScale: 1.5 },
  jawAngle: { gain: 1.9, damping: 0.68, speedScale: 1.65 },
};
