export const WRECKERSAURUS_SCALE = 2.25;
export const WRECKERSAURUS_SOURCE_ART_SCALE = 0.0118;
export const WRECKERSAURUS_ART_SCALE = WRECKERSAURUS_SOURCE_ART_SCALE * WRECKERSAURUS_SCALE;
export const WRECKERSAURUS_HEAD_JAW_ART_SCALE = WRECKERSAURUS_ART_SCALE;
export const WRECKERSAURUS_DRIVE_SPEED = 20;
export const WRECKERSAURUS_MOTOR_TORQUE = 980;
export const WRECKERSAURUS_WHEEL_FRICTION = 9.5;
export const WRECKERSAURUS_SUSPENSION_FREQUENCY = 7.4;
export const WRECKERSAURUS_SUSPENSION_DAMPING = 0.74;
export const WRECKERSAURUS_TREAD_LINK_FREQUENCY = 18;
export const WRECKERSAURUS_CHASSIS_DENSITY = 0.82;
export const WRECKERSAURUS_WHEEL_DENSITY = 1.2;
export const WRECKERSAURUS_ARM_SPEED = 2.7;
export const WRECKERSAURUS_DIRECT_TARGET_SPEED = 9.2;
export const WRECKERSAURUS_DIRECT_HEAD_TURN_SPEED = 1.45;
export const WRECKERSAURUS_JAW_OPEN_ANGLE = 0.48;
export const WRECKERSAURUS_JAW_CLOSED_ANGLE = -0.2;
export const WRECKERSAURUS_COLLISION_GROUP = -3;
export const WRECKERSAURUS_FACING_RIGHT = 1;
export const WRECKERSAURUS_FACING_LEFT = -1;
export const WRECKERSAURUS_GAMEPAD_DEADZONE = 0.14;
export const WRECKERSAURUS_FLIP_UPWARD_IMPULSE = 780;
export const WRECKERSAURUS_FLIP_SIDE_IMPULSE = 120;
export const WRECKERSAURUS_FLIP_ANGULAR_IMPULSE = 900;
export const WRECKERSAURUS_FRACTURE_LOAD_MULTIPLIER = 0.78;
export const WRECKERSAURUS_ARM_SERVO = {
  boomAngle: { gain: 3.1, damping: 0.28, speedScale: 1 },
  stickAngle: { gain: 2.8, damping: 0.34, speedScale: 1.02 },
  headAngle: { gain: 1.55, damping: 0.72, speedScale: 0.7 },
  jawAngle: { gain: 1.45, damping: 0.68, speedScale: 0.82 },
};
